version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "22181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: loguser
      POSTGRES_PASSWORD: logpass
      POSTGRES_DB: loganalytics
    # No ports exposed — internal network use only

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  workload:
    build: ./workload
    depends_on:
      - api

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - postgres
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:


